10 post article id comments
Raedaw/backend-project pull request #8
Opened 2022-07-06 15:14 UTC by Raedaw

ticket 10 POST /api/articles/:article_id/comments  with error handling

2022-07-06 15:34 UTC, Poonam-raj requested changes
few more tests needed but looking strong 🎉 Throw this back when amendments are made

2022-07-06 15:34 UTC, Poonam-raj commented on __tests__/app.test.js
> +        expect(comment).toHaveProperty("comment_id");
I'd want to check the comment_id is what we expect it to be, so more specific check here

2022-07-06 15:34 UTC, Poonam-raj commented on __tests__/app.test.js
> +      });
I'd also check if `username` was missing that the same error was thrown

2022-07-06 15:34 UTC, Poonam-raj commented on __tests__/app.test.js
> +        expect(msg).toBe("Invalid input");
Message would more likely want to be `invalid article id` or something similar here

2022-07-06 15:34 UTC, Poonam-raj commented on __tests__/app.test.js
> +});
please also test for when a username is present but not found in the database - this would be a 404 not found

2022-07-07 14:24 UTC, Rayhaan2k9 commented on error-handling.js
> +
Not sure you need this error handler as your error handler on line 10 should do this for you. But happy to approve anyway :)

2022-07-07 14:25 UTC, Rayhaan2k9 approved these changes
Just a little suggestion but happy to approve :)

2022-07-07 14:27 UTC, merged